apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-thigie
spec:
  ttlSecondsAfterEmpty: 120
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["c6g.4xlarge"]
  limits:
    resources:
      cpu: 5000
  provider:
    instanceProfile: eks-on-ec2-karpenter-instance-profile-thingie
    launchTemplate: eks-on-ec2-karpenter-karpenter-lt
    subnetSelector:
      karpenter-yas: '*'
    securityGroupSelector:
      karpenter-yas: '*'
