# FROM public.ecr.aws/docker/library/python:3.10.1-windowsservercore-1809
FROM python:3.10.1-windowsservercore-1809

RUN pip install poetry

WORKDIR /app

COPY pyproject.toml ./
COPY poetry.toml ./
COPY poetry.lock ./

RUN poetry install --no-dev

COPY . .

EXPOSE 5002
ENTRYPOINT ["poetry", "run"]
CMD ["waitress-serve", "--port=5002", "app:app" ]
